#!/usr/bin/php

<?php

require_once __DIR__ . '/vendor/autoload.php';

if ($argc <= 1) {
    echo "Not enough arguments. At least one expected.\n";
    exit(12);
}

$parser = new \Plang\frontend\Parser();
$file = $argv[1];
$program = $parser->parse($file);

$plang = new \Plang\Plang([]);
$plang->addPackage(new \Plang\package\StdPackage());

$plang->execute($program);

